name: Changesets
on:
  push:
    branches:
      - main
env:
  CI: true
  # PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install pnpm
        run: npm i pnpm@latest -g
      # - name: setup pnpm config
      #  run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: Setup npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
          //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          EOF
      - name: install dependencies
        run: pnpm install
      - name: create and publish versions
        run: pnpm ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
