name: Publish Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    permissions:
      packages: write
      contents: read
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js ${{ matrix.node-version }} and Authenticate with GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true

      - name: Replace GH_ACCESS_TOKEN in .npmrc
        run: sed -i "s/\${GH_ACCESS_TOKEN}/${GH_ACCESS_TOKEN}/g" .npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Publish packages
        run: pnpm publish -r --access=restricted
